setwd("C:/Users/lpost/My Documents/Coursera/04 - Exploratory Data Analysis")
DataFile <- read.csv("household_power_consumption.txt", header=T, sep=';', na.strings="?", nrows=2075258, check.names=F, stringsAsFactors=F, comment.char="", quote='\"')
SubsetData <- subset(DataFile, Date %in% c("1/2/2007","2/2/2007"))
SubsetData$Date <- as.Date(SubsetData$Date, format="%d/%m/%Y")
DateTime <- paste(as.Date(SubsetData$Date), SubsetData$Time)
SubsetData$Datetime <- as.POSIXct(DateTime)
par(mfrow=c(2,2), mar=c(4,4,2,1), oma=c(0,0,2,0))
plot(SubsetData$Global_active_power~SubsetData$Datetime, type="l", xlab="", ylab="Global Active Power")
plot(SubsetData$Voltage~SubsetData$Datetime, type="l", xlab="datetime", ylab="Voltage")
plot(SubsetData$Sub_metering_1~SubsetData$Datetime, type="l", xlab="", ylab="Energy sub metering")
lines(SubsetData$Sub_metering_2~SubsetData$Datetime, col="red")
lines(SubsetData$Sub_metering_3~SubsetData$Datetime, col="blue")
legend("topright", col=c("black", "red", "blue"), lty=c(1,1), cex=.5, bty="n", legend=c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
plot(SubsetData$Global_reactive_power~SubsetData$Datetime, type="l", xlab="datetime", ylab="Global_reactive_power")
dev.copy(png, file="plot4.png", width=480, height=480)
dev.off()