setwd("C:/Users/lpost/My Documents/Coursera/04 - Exploratory Data Analysis")
DataFile <- read.csv("household_power_consumption.txt", header=T, sep=';', na.strings="?", nrows=2075258, check.names=F, stringsAsFactors=F, comment.char="", quote='\"')
SubsetData <- subset(DataFile, Date %in% c("1/2/2007","2/2/2007"))
SubsetData$Date <- as.Date(SubsetData$Date, format="%d/%m/%Y")
hist(SubsetData$Global_active_power, main="Global Active Power", xlab="Global Active Power (kilowatts)", ylab="Frequency", col="red")
dev.copy(png, file="plot1.png")
dev.off()