setwd("C:/Users/lpost/My Documents/Coursera/04 - Exploratory Data Analysis")
DataFile <- read.csv("household_power_consumption.txt", header=T, sep=';', na.strings="?", nrows=2075258, check.names=F, stringsAsFactors=F, comment.char="", quote='\"')
SubsetData <- subset(DataFile, Date %in% c("1/2/2007","2/2/2007"))
SubsetData$Date <- as.Date(SubsetData$Date, format="%d/%m/%Y")
DateTime <- paste(as.Date(SubsetData$Date), SubsetData$Time)
SubsetData$Datetime <- as.POSIXct(DateTime)
plot(SubsetData$Sub_metering_1~SubsetData$Datetime, type="l", xlab="", ylab="Energy sub metering")
lines(SubsetData$Sub_metering_2~SubsetData$Datetime, col="red")
lines(SubsetData$Sub_metering_3~SubsetData$Datetime, col="blue")
legend("topright", col=c("black", "red", "blue"), lty=1, lwd=2, legend=c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
dev.copy(png, file="plot3.png", width=480, height=480)
dev.off()