setwd("C:/Users/lpost/My Documents/Coursera/04 - Exploratory Data Analysis")
DataFile <- read.csv("household_power_consumption.txt", header=T, sep=';', na.strings="?", nrows=2075258, check.names=F, stringsAsFactors=F, comment.char="", quote='\"')
SubsetData <- subset(DataFile, Date %in% c("1/2/2007","2/2/2007"))
SubsetData$Date <- as.Date(SubsetData$Date, format="%d/%m/%Y")
DateTime <- paste(as.Date(SubsetData$Date), SubsetData$Time)
SubsetData$Datetime <- as.POSIXct(DateTime)
plot(SubsetData$Global_active_power~SubsetData$Datetime, type="l", xlab="", ylab="Global Active Power (kilowatts)")
dev.copy(png, file="plot2.png", width=480, height=480)
dev.off()